version: "3.2"

services:
  python:
    build: .
    restart: always
    ports:
      - "8090:80"
  postgres:
    restart: always
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=example
    volumes:
      - /srv/docker/postgresql-data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"